plugins {
    id "com.android.application"
}

android {
    namespace "com.zwerk.weather"
    compileSdk 36

    defaultConfig {
        applicationId "com.zwerk.weather"
        minSdk 28
        targetSdk 36
        versionCode 9
        versionName "1.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
